name: CopyBara-Push

on: push

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.3
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          ssh_key: ${{ secrets.DESTINATION_SSH_KEY }}
          sot_repo: https://github.com/sriharibtl/copybarasource.git
          destination_repo: https://github.com/sriharibtl/copybaradestination.git
          workflow: default
          custom_config: copy.bara.sky
          copybara_options: --init-history
