on: push

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11.0.12+7
          distribution: temurin
          java-package: jdk
      - name: checkout copybara repo
        uses: actions/checkout@v2
        with:
          repository: google/copybara
          path: copybara
      - name: Setup Bazel
        uses: holvonix-open/setup-bazelisk@v0.6.1
      - run: cd copybara; bazel build java/com/google/copybara
      - run: ls; bazel-bin/java/com/google/copybara/copybara ../copy.bara.sky
