name: CopyBara-Push

on: push

jobs:
  copybara:
    name: Copy bara code push
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - uses: wilmol/copybara-action@v1
        with:
          git_name: sriharibtl
          git_email: sbn@infoblox.com
          ssh_key: ${{ secrets.DESTINATION_SSH_KEY }}
          path: .
