on: push

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          sot_repo: sriharibtl/copybarasource
          sot_branch: main
          destination_repo: sriharibtl/copybaradestination
          workflow: create
          custom_config: copy.bara.sky
