on: push

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wilmol/copybara-action@v1
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          git_name: sriharibtl
          git_email: sbn@infoblox.com
          path: copy.bara.sky
