name: CopyBara-Push

on: push

jobs:
  copybara:
    name: Copy bara code push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copybara Action 2
      # You may pin to the exact commit or the version. bg
      # uses: Olivr/copybara-action@19127a45a319c24f79175814af5cc1c2a83e9b05
        uses: Olivr/copybara-action@v1.2.2
        with:
          ssh_key: ${{ secrets.DESTINATION_SSH_KEY }}
          sot_repo: https://github.com/sriharibtl/copybarasource.git
          sot_branch: main
          destination_repo: https://github.com/sriharibtl/copybaradestination.git
          destination_branch: main
